/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgp.ca.presentation;

import java.awt.Color;
import sgp.ca.businesslogic.CollaboratorDao;
import sgp.ca.domain.Collaborator;

/**
 *
 * @author Esteban
 */
public class AddCollaborator extends javax.swing.JFrame {

    /**
     * Creates new form AddCollaborator
     */
    public AddCollaborator() {
        initComponents();
        this.setLocation(380,200);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTName = new javax.swing.JTextField();
        jLName = new javax.swing.JLabel();
        jLLastName = new javax.swing.JLabel();
        jTLastName = new javax.swing.JTextField();
        jLMotherLastName = new javax.swing.JLabel();
        jTMotherLastName = new javax.swing.JTextField();
        jLEnrollmentOrId = new javax.swing.JLabel();
        jTEnrollmentOrId = new javax.swing.JTextField();
        jLCollaborator = new javax.swing.JLabel();
        jCCollaborator = new javax.swing.JComboBox<>();
        jBCancel = new javax.swing.JButton();
        jBRegister = new javax.swing.JButton();
        jCMember = new javax.swing.JComboBox<>();
        jLMember = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTMail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTCellPhoneNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNameActionPerformed(evt);
            }
        });
        jTName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNameKeyTyped(evt);
            }
        });
        getContentPane().add(jTName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 100, -1));

        jLName.setText("Nombre:");
        getContentPane().add(jLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLLastName.setText("Apellido Paterno:");
        getContentPane().add(jLLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jTLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTLastNameActionPerformed(evt);
            }
        });
        jTLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTLastNameKeyTyped(evt);
            }
        });
        getContentPane().add(jTLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 100, -1));

        jLMotherLastName.setText("Apellido Materno:");
        getContentPane().add(jLMotherLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jTMotherLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMotherLastNameActionPerformed(evt);
            }
        });
        jTMotherLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTMotherLastNameKeyTyped(evt);
            }
        });
        getContentPane().add(jTMotherLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 100, -1));

        jLEnrollmentOrId.setText("Matricula/Id:");
        getContentPane().add(jLEnrollmentOrId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jTEnrollmentOrId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEnrollmentOrIdActionPerformed(evt);
            }
        });
        getContentPane().add(jTEnrollmentOrId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 100, -1));

        jLCollaborator.setText("Tipo de Colaborador:");
        getContentPane().add(jLCollaborator, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        jCCollaborator.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colaborador", "Estudiante" }));
        jCCollaborator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCCollaboratorActionPerformed(evt);
            }
        });
        getContentPane().add(jCCollaborator, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 110, -1));

        jBCancel.setText("Cancelar");
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jBCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jBRegister.setText("Registrar");
        jBRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jBRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        jCMember.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colaborador", "Integrante" }));
        jCMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCMemberActionPerformed(evt);
            }
        });
        getContentPane().add(jCMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 110, -1));

        jLMember.setText("Tipo de Integrante:");
        getContentPane().add(jLMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel3.setText("Celular:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        jTMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMailActionPerformed(evt);
            }
        });
        getContentPane().add(jTMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 110, -1));

        jLabel2.setText("Correo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jTCellPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTCellPhoneNumberKeyTyped(evt);
            }
        });
        getContentPane().add(jTCellPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgp/ca/presentation/Images/registro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -310, 610, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNameActionPerformed

    private void jTLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTLastNameActionPerformed

    private void jTMotherLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMotherLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMotherLastNameActionPerformed

    private void jTEnrollmentOrIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEnrollmentOrIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTEnrollmentOrIdActionPerformed

    private void jBRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegisterActionPerformed
        int confirmation = 0;
        boolean confirmationCollaborator = false;
        Collaborator collaborator = new Collaborator();
        String [] data = new String [7];
        data = recoverData();
        if(data==null){
            
        }else{
            CollaboratorDao collaboratorDao = new CollaboratorDao();
            collaborator = collaboratorDao.createCollaborator(data);
            confirmationCollaborator = collaboratorDao.verifyCollaborator(collaborator);
            if(confirmationCollaborator==true){
                javax.swing.JOptionPane.showMessageDialog(this,"Este Colaborador ya existe en el sistema \n","Integrante Repetido",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }else{
                confirmation = collaboratorDao.Collaborator(collaborator);
            }if(confirmation==1){
                javax.swing.JOptionPane.showMessageDialog(this,"Colaborador registrado con éxito \n","Integrante Registrado",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                cleanText();
            }if(confirmation==2){
                javax.swing.JOptionPane.showMessageDialog(this,"No se puede registrar miembros en este momento, intentelo más tarde \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBRegisterActionPerformed

    private void jCMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCMemberActionPerformed
        if(jCMember.getSelectedItem()=="Integrante"){
            AddMember addMember = new AddMember();
            addMember.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jCMemberActionPerformed

    private void jTMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMailActionPerformed

    private void jTNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNameKeyTyped
        char valide = evt.getKeyChar();
        if((valide<'a'|| valide>'z') && (valide<'A'||valide>'Z') &&(valide<' ' || valide>' '))evt.consume();
    }//GEN-LAST:event_jTNameKeyTyped

    private void jTLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTLastNameKeyTyped
        char valide = evt.getKeyChar();
        if((valide<'a'|| valide>'z') && (valide<'A'||valide>'Z') &&(valide<' ' || valide>' '))evt.consume();
    }//GEN-LAST:event_jTLastNameKeyTyped

    private void jTMotherLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTMotherLastNameKeyTyped
        char valide = evt.getKeyChar();
        if((valide<'a'|| valide>'z') && (valide<'A'||valide>'Z') &&(valide<' ' || valide>' '))evt.consume();
    }//GEN-LAST:event_jTMotherLastNameKeyTyped

    private void jTCellPhoneNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCellPhoneNumberKeyTyped
        char valide = evt.getKeyChar();
        if(valide<'0'||valide>'9')evt.consume();
    }//GEN-LAST:event_jTCellPhoneNumberKeyTyped

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        DisplaysMember displaysMember = new DisplaysMember();
        displaysMember.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBCancelActionPerformed

    private void jCCollaboratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCCollaboratorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCCollaboratorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCollaborator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCollaborator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCollaborator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCollaborator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCollaborator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBRegister;
    private javax.swing.JComboBox<String> jCCollaborator;
    private javax.swing.JComboBox<String> jCMember;
    private javax.swing.JLabel jLCollaborator;
    private javax.swing.JLabel jLEnrollmentOrId;
    private javax.swing.JLabel jLLastName;
    private javax.swing.JLabel jLMember;
    private javax.swing.JLabel jLMotherLastName;
    private javax.swing.JLabel jLName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTCellPhoneNumber;
    private javax.swing.JTextField jTEnrollmentOrId;
    private javax.swing.JTextField jTLastName;
    private javax.swing.JTextField jTMail;
    private javax.swing.JTextField jTMotherLastName;
    private javax.swing.JTextField jTName;
    // End of variables declaration//GEN-END:variables

    private String[] recoverData() {
        String [] data = new String[7];
        boolean valide = false;
        valide = valideData();
        if(valide == false){
            data[0]=jTName.getText();
            data[1]=jTLastName.getText();
            data[2]=jTMotherLastName.getText();
            data[3]=jTEnrollmentOrId.getText();
            data[4]=(String)jCCollaborator.getSelectedItem();
            data[5]=jTMail.getText();
            data[6]=jTCellPhoneNumber.getText();
        }else{
            data = null;
        }
        return data;
    }

    private boolean valideData() {
        boolean valide = false;
        if(jTName.getText().equals("")){
            jTName.setBackground(Color.red);
            valide = true;
        }else{
            jTName.setBackground(Color.white);
        }
        if(jTLastName.getText().equals("")){
            jTLastName.setBackground(Color.red);
            valide = true;
        }else{
            jTLastName.setBackground(Color.white);
        }
        if(jTMotherLastName.getText().equals("")){
            jTMotherLastName.setBackground(Color.red);
            valide = true;
        }else{
            jTMotherLastName.setBackground(Color.white);
        }
        if(jTEnrollmentOrId.getText().equals("")){
            jTEnrollmentOrId.setBackground(Color.red);
            valide = true;
        }else{
            jTEnrollmentOrId.setBackground(Color.white);
        }
        if(jTCellPhoneNumber.getText().equals("")){
            jTCellPhoneNumber.setBackground(Color.red);
            valide = true;
        }else{
            jTCellPhoneNumber.setBackground(Color.white);
        }
        if(jTMail.getText().equals("")){
            jTMail.setBackground(Color.red);
            valide = true;
        }else{
            jTMail.setBackground(Color.white);
        }
        return valide;
    }
    
    public void cleanText(){
        jTName.setText("");
        jTLastName.setText("");
        jTMotherLastName.setText("");
        jTCellPhoneNumber.setText("");
        jTEnrollmentOrId.setText("");
        jTMail.setText("");
    }
}
